### ISSUE TITLE
How to use Document store?

### ISSUE THREAD

**Issue by frudas24** [orbitdb/orbit-db-cli#7]
Hi,
repo: git clone https://github.com/orbitdb/orbit-db-cli.git
how to replicate:
orbitdb create docdata docstore
orbitdb put docdata TestWordDoc.doc

the error:
Error: Unexpected token T in JSON at position 0

**Comment by haadcode** [comment]
Hi @frudas24, thanks for issue!

The docstore is mean to be used for "documents" which in orbit-db's case mean JSON data. Take a look at the [demo commands and output for an example](https://github.com/orbitdb/orbit-db-cli#demo). 

After creating a document database with:
```
orbitdb create demo docstore
```

Instead of adding a *file* to the document store, you add a JSON object (note that the address will be different, copy it from the output of the create command):
```
orbitdb put /orbitdb/QmcE2HMrDTL3SFV1rcB5GaJVSJFfpFsnfTM4qK8SRScjyj/demo "{\"_id\":1,\"name\":\"frudas24 was here\"}" --indexBy name
```

You can then search by the contents of the field used for indexing, eg. search from all `name` fields:
```
orbitdb search /orbitdb/QmcE2HMrDTL3SFV1rcB5GaJVSJFfpFsnfTM4qK8SRScjyj/demo frudas24
```

Hope this helps and don't hesitate to ask  if you need more help! 👍

**Comment by frudas24** [comment]
ok thanks for the answer.
