### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by kidinamoto01** [orbitdb/orbit-db-cli#9]
hey,
I'm new to orbit-db and I got some errors when installing orbit-db-cli
my command is 
`git clone https://github.com/orbitdb/orbit-db-cli.git
cd orbit-db-cli
nom install`

I tried `orbitdb version`
Error ` orbitdb: command not found`

I'm using npm@5.5.1& node@v8.9.0

Thanks for your help

Cheers^^

**Comment by haadcode** [comment]
Thanks for opening the issue @kidinamoto01! 

When cloning from Github, the `orbitdb` command doesn't become automatically available. It's only available when installed from npm.

In order to use the CLI when installed from Git, you can run it with:
`node src/bin help`

Let me know if this doesn't solve your problem.

**Comment by kidinamoto01** [comment]
Thanks, it worked. (my bad, I didn't read the readme carefully)

Could you show me the link of some documents? I'd love to know more about it. And I am think about merge [ipfs_eth_import](https://github.com/ipfs/go-ipld-eth-import) with orbitdb.  The two should work perfectly together ^^

**Comment by haadcode** [comment]
@kidinamoto01 perhaps you could explain a little what you aim to achieve with orbitdb+ipfs-eth-import so that I can point you to the right direction? how do you want to put them together?

The current documentation is at https://github.com/orbitdb/orbit-db. That should get you started and make sure to check the examples too. Feel free to open new issues or ask more questions, happy to help!

**Comment by kidinamoto01** [comment]
@haadcode Thanks!
I am working on a project of tracking smart contract in Ethereum, and I aim to import transaction logs into orbit-db.  ipfs_eth_import  seems like a good solution to get the data from levelDB into IPFS. It digest each block information and traverse through transactions.
Really appreciate your opinions
Cheers ^^

**Comment by haadcode** [comment]
@kidinamoto01 it depends on what you aim to do with the data that you get from the Ethereum transaction logs and if you need to have them tracked "in real-time" (as opposed batch processing at intervals), but to me it sounds like you don't necessarily need OrbitDB. I don't understand your full use case yet, so I might be wrong.

What could get you to your goal, might be [IPLD](https://github.com/ipld) and more specifically the Ethereum resolvers for IPLD: https://github.com/ipld/js-ipld-ethereum. What you could do is to import the eth logs to IPFS with ipfs-eth-import and then use IPLD (the ethereum resolvers in the link above) to query it. This works if you don't need real-time updates and don't need to structure your data, say to new indexes.

Would that satisfy your use case?

**Comment by kidinamoto01** [comment]
Thanks, I'll look into it. ^^

**Comment by haadcode** [comment]
Cool. Gonna close this issue as the original problem was solved. Feel free to re-open it if you still have the problem and please do open new issues if you have more questions. Happy to help!
